use_conda: True

method_names:
  bwa: "BWA MEM"
  strobealign: "Strobealign"
  minimap2: "Minimap2"


runs:
  mapping:
    name: "Mapping reads"
    tools: [ "bwa", "strobealign", "minimap2"]
    output_file_ending: ".sam"
    validate_equal: false
    runs:
      small: "dataset1"
      big: "dataset2"


truth_datasets:
  hg002:
    vcf_url: "https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/AshkenazimTrio/HG002_NA24385_son/NISTv4.2.1/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark.vcf.gz"

  hg003:
    vcf_url: "https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/AshkenazimTrio/HG003_NA24149_father/NISTv3.3.2/GRCh38/HG003_GRCh38_GIAB_highconf_CG-Illfb-IllsentieonHC-Ion-10XsentieonHC_CHROM1-22_v.3.3.2_highconf.vcf.gz"


simulations:
  dataset1:
    genome: "hg38"
    individual: "hg002"
    n_reads: 2000
    chromosomes: "chr20,chr21"
    mason_flags: ""
    paired_type: "single-end" #  or paired-end

  dataset2:
    genome: "hg38"
    individual: "hg002"
    n_reads: 200000
    chromosomes: "chr17,chr18,chr19,chr20,chr21"

