use_conda: True

method_names:
  bwa: "BWA MEM"
  strobealign: "Strobealign"
  minimap2: "Minimap2"


runs:
  mapping:
    name: "Mapping reads"
    tools: [ "bwa", "strobealign", "minimap2"]
    output_file_ending: ".sam"
    validate_equal: false
    runs:
      small: "dataset1"
      big: "dataset2"


variant_sources:
  hg002:
    genome: "hg38"
    vcf_url: "https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/AshkenazimTrio/HG002_NA24385_son/NISTv4.2.1/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark.vcf.gz"

  hg003:
    genome: "hg38"
    vcf_url: "https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/AshkenazimTrio/HG003_NA24149_father/NISTv3.3.2/GRCh38/HG003_GRCh38_GIAB_highconf_CG-Illfb-IllsentieonHC-Ion-10XsentieonHC_CHROM1-22_v.3.3.2_highconf.vcf.gz"


illumina_error_profiles:
  low_error:
    deletion_prob: 0.00001
    insertion_prob: 0.00001
    mismatch_scale: 0.2

  medium_error:
    deletion_prob: 0.00005
    insertion_prob: 0.00005
    mismatch_scale: 1.0

  high_error:
    deletion_prob: 0.0005
    insertion_prob: 0.0005
    mismatch_scale: 3.0


# Configuration for "genome" (individuals) that reads can be sequenced from
# Genomes are based on a reference genome
# each genomes can have multiple individuals
# simulated_reads should not be directory

individuals:
  hg002_small:
    variant_source: "hg002"
    chromosomes: "chr20,chr21"

  hg002_medium:
    variant_source: "hg002"
    chromosomes: "chr17,chr18,chr19,chr20,chr21"



genomes:
  hg38:
    hg002:
      vcf_url: "https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/AshkenazimTrio/HG002_NA24385_son/NISTv4.2.1/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark.vcf.gz"

      small:
        chromosomes: "chr20,chr21"
      medium:
        chromosomes: "chr17,chr18,chr19,chr20,chr21"

    hg003:
      # ..