use_conda: True

# name of all methods
methods: ["bwa", "bowtie2", "minimap2"]

# things that can be measured and represented as a
# number for each method. These types can be specified on axis/facets for plot_types.
result_types: [
  "runtime",
  "memory_usage",
  "mapping_recall",
  "mapping_one_minus_precision",
  "mapping_f1_score",
  "variant_calling_precision",
  "variant_calling_one_minus_precision",
  "variant_calling_recall",
  "variant_calling_f1score",
  "peak_calling_accuracy"
]

# Default parameter groups. Will be used for plotting if not overridden in plot config in plots.yaml
default_parameter_sets:
  genome_build: [hg38, sacCer3]
  individual: [hg002]
  dataset_size: [small", medium, big]
  read_type: [single_end, paired_end]
  error_profile: [low_error, medium_error, high_error]
  read_length: [75, 150, 250]
  n_reads: [1000, 10000, 100000, 1000000, 10000000]
  method: [bwa, minimap, strobealign, bowtie2]
  n_threads: [1, 4, 8, 16]
  min_mapq: [0, 10, 20, 30, 40]
  variant_filter: [all, variants, nonvariants]
  variant_calling_type: [snps, indels]
  n_peaks: [50, 100, 500]
  spot: [0.2, 0.4, 0.6]


genomes:
  hg38:  # UCSC id of reference genome
    hg002:  # a descriptive name [a-zA-z0-9]
      simulated: False
      # url to the genomic variants and truth regions for this individual
      vcf_url: "https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/AshkenazimTrio/HG002_NA24385_son/NISTv4.2.1/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark.vcf.gz"
      truth_regions: "https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/AshkenazimTrio/HG002_NA24385_son/NISTv4.2.1/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark_noinconsistent.bed"

      # "genomes" that are used for benchmarking
      # Specify small and medium for quicker runs.
      # The big should be the full genome (* means all chromosomes)
      small:
        chromosomes: "chr20,chr21"
        genome_size: 111154150
      medium:
        chromosomes: "chr17,chr18,chr19,chr20,chr21"
        genome_size: 333402492
      big:
        chromosomes: "chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY"
        genome_size: 3000000000
    hg003:
      # not implemented

  # yeast
  sacCer3:
    simulated:
      simulated: True
      small:
        chromosomes: "chrIV,chrXV"
        genome_size: 2623224
      medium:
        chromosomes: "chrI,chrII,chrIII,chrIV,chrV"
        genome_size: 3468829



# Error profiles. The names (e.g. low_error) are used as parameters
illumina_error_profiles:
  low_error:
    deletion_prob: 0.00001
    insertion_prob: 0.00001
    mismatch_scale: 0.2

  medium_error:
    deletion_prob: 0.00005
    insertion_prob: 0.00005
    mismatch_scale: 1.0

  high_error:
    deletion_prob: 0.0005
    insertion_prob: 0.0005
    mismatch_scale: 3.0


mason_variator_parameters:
   "--snp-rate 0.001
   --small-indel-rate 0.0001
   --min-small-indel-size 1
   --max-small-indel-size 6
   --sv-indel-rate 0
   --sv-inversion-rate 0
   --sv-translocation-rate 0
   --sv-duplication-rate 0
   "