# This file contains all configuration for the plots (reports) that can be generated

# List of quick and small plots used for testing
test_plots: [f1_score, accuracy_for_various_mapq_thresholds, memory]
# List of plots that will be generated every night
#nightly_plots: [accuracy_on_various_read_lengths, variant_calling_accuracy]
nightly_plots: [
  variant_calling_accuracy_vs_mapq_threshold,
  accuracy_for_various_mapq_thresholds_human_whole_genome,
  runtime_human_whole_genome,
  variant_calling_accuracy,
  accuracy_vs_read_length_and_error_profile_human_whole_genome,
  memory_human_whole_genome
]

# Dimensions that can be used when defining plot_types
plotting_dimensions: ["x", "y", "labels", "color", "facet_col", "facet_row"]


# Axis/titles/etc that will be replaced in plots
pretty_names:
  variant_calling_precision: Precision
  variant_calling_recall: Recall
  variant_calling_f1score: F1 Score
  one_minus_precision: 1-Precision
  recall: Recall
  runtime: Runtime (sec)
  n_threads: Number of threads
  whole_genome_single_end: Single-end reads
  whole_genome_paired_end: Paired-end reads
  read_length: Read length (nt)
  f1_score: F1 score
  low_error: Low error
  medium_error: Medium error
  high_error: High error


# Plots
plots:
  generic:
    # used as a dummy for plots that are not defined
    plot_type: ""
  plot1:
    plot_type: accuracy_vs_read_length
    parameters:
      read_type: whole_genome_single_end
  f1_score:
    plot_type: f1_score
  accuracy_vs_read_length_and_error_profile:
    plot_type: accuracy_vs_read_length_and_error_profile
    parameters:
      method: including_strobealign
  accuracy_for_various_mapq_thresholds:
    plot_type: accuracy
    parameters:
      method: all_methods
  accuracy_on_various_read_lengths:
    plot_type: accuracy_on_various_read_lengths
  accuracy_f1_score:
    plot_type: accuracy_f1_score
    parameters:
      method: including_strobealign
  memory:
    plot_type: memory_usage
  variant_calling_accuracy:
    parameters:
      n_reads: "20000000"
    plot_type: variant_calling_accuracy
  variant_calling_accuracy_test:
    parameters:
      n_reads: "100000"
    plot_type: variant_calling_accuracy
  runtime:
    plot_type: runtime
  runtime_with_varying_number_of_threads:
    plot_type: runtime_with_varying_number_of_threads
    parameters:
      n_reads: "100000"

  accuracy_for_various_mapq_thresholds_human_whole_genome:
    plot_type: accuracy
    parameters:
      dataset_size: big
      n_reads: "1000000"

  runtime_human_whole_genome:
    plot_type: runtime_with_varying_number_of_threads
    parameters:
      dataset_size: big
      n_reads: "10000000"
      method: including_strobealign

  memory_human_whole_genome:
    plot_type: memory_usage
    parameters:
      dataset_size: big
      n_reads: "200000"

  variant_calling_accuracy_human_whole_genome:
    plot_type: variant_calling_accuracy
    parameters:
      dataset_size: big
      n_reads: "5000000"

  accuracy_vs_read_length_and_error_profile_human_whole_genome:
    plot_type: accuracy_vs_read_length_and_error_profile
    parameters:
      dataset_size: big
      n_reads: "250000"
      
  variant_calling_accuracy_vs_mapq_threshold_quick:
    plot_type: variant_calling_accuracy_vs_mapq_threshold
    parameters:
      datset_size: small
      n_reads: "200000"
      n_threads: 2
      
  variant_calling_accuracy_vs_mapq_threshold:
    plot_type: variant_calling_accuracy_vs_mapq_threshold
    parameters:
      datset_size: medium
      n_reads: "15000000"
      n_threads: 8
  
  f1_score_vs_read_length:
    plot_type: f1_score_vs_read_length
    parameters:
      read_length: read_lengths_fine
      n_threads: 4
      n_reads: 40000

# The following defines different type of plots
# This includes only the description of the structure of each plot, not what values are used for the variables
# Each of x_axis, y_axis, category_variable, color, labels, facet_col, facet_row
# should be either a result_type or a parameter_type if set

plot_types:
  f1_score:
    type: bar
    x: "method"
    y: "f1_score"
  accuracy:
    type: line
    markers: True
    x: one_minus_precision
    y: recall
    labels: min_mapq
    color: method
    facet_col: variant_filter
    facet_row: read_type
    layout:
      xaxis_type: log
  accuracy_on_various_read_lengths:
    type: line
    markers: True
    x: "one_minus_precision"
    y: "recall"
    labels: "min_mapq"
    color: "method"
    facet_col: "read_length"
  accuracy_vs_read_length_single_method:
    type: "line"
    x: "read_length"
    y: "f1_score"
  accuracy_vs_read_length_and_error_profile:
    type: "line"
    x: "read_length"
    y: "f1_score"
    color: "method"
    facet_col: "variant_filter"
    facet_row: "error_profile"
  runtime:
    type: "bar"
    y: "runtime"
    x: "method"
  runtime_with_varying_number_of_threads:
    type: line
    y: runtime
    x: n_threads
    color: method
    facet_col: read_type
    facet_row: read_length
  memory_usage:
    type: bar
    y: memory_usage
    x: method
  variant_calling_accuracy:
    type: "scatter"
    y: variant_calling_recall
    x: variant_calling_precision
    color: method
    facet_col: variant_calling_type
  accuracy_f1_score:
    type: bar
    y: f1_score
    x: method
    facet_col: read_type
  variant_calling_accuracy_vs_mapq_threshold:
    type: line
    markers: true
    y: variant_calling_recall
    x: variant_calling_one_minus_precision
    labels: min_mapq
    color: method
  f1_score_vs_read_length:
    type: line
    y: f1_score
    x: read_length
    color: method
    facet_col: variant_filter
    facet_row: read_type