# This file contains all configuration for the plots (reports) that can be generated

# List of quick and small plots used for testing
test_plots: [
  peak_calling_accuracy_test,
  f1_score,
  accuracy_for_various_mapq_thresholds_yeast,
  peak_calling_accuracy_vs_read_length_yeast,
  memory_test,
  runtime_test,
  #variant_calling_accuracy_test
]

# List of plots that will be generated every night
#nightly_plots: [accuracy_on_various_read_lengths, variant_calling_accuracy]
nightly_plots: [
  f1_score_vs_read_length,
  accuracy_for_various_mapq_thresholds_human_whole_genome,
  accuracy_vs_read_length_and_error_profile_human_whole_genome,
  variant_calling_accuracy_vs_mapq_threshold,
  peak_calling_accuracy_vs_read_length_human,
  runtime_human_whole_genome,
  memory_human_whole_genome,
]


# Axis/titles/etc that will be replaced in plots
pretty_names:
  variant_calling_precision: Precision
  variant_calling_one_minus_precision: 1-Precision
  variant_calling_recall: Recall
  variant_calling_f1score: F1 Score
  MappingOneMinusPrecision: 1-Precision
  MappingRecall: Recall
  MappingF1Score: F1 Score
  runtime: Runtime (sec)
  n_threads: Number of threads
  single_end: Single-end reads
  paired_end: Paired-end reads
  read_length: Read length (nt)
  f1_score: F1 score
  low_error: Low error
  medium_error: Medium error
  high_error: High error


# Plots
plots:
  generic:
    # used as a dummy for plots that are not defined
    plot_type: ""

  plot1:
    plot_type: accuracy_vs_read_length
    parameters:
      read_type: whole_genome_single_end

  f1_score:
    title: "F1 score"
    plot_type: f1_score
    parameters:
      n_reads: 1234

  accuracy_vs_read_length_and_error_profile:
    plot_type: accuracy_vs_read_length_and_error_profile

  accuracy_on_various_read_lengths:
    plot_type: accuracy_on_various_read_lengths

  accuracy_f1_score:
    plot_type: accuracy_f1_score

  memory:
    plot_type: memory_usage

  memory_test:
    plot_type: memory_usage
    parameters:
      n_reads: 1000
      genome_build: sacCer3
      individual: simulated

  runtime_test:
    plot_type: runtime
    parameters:
      n_reads: 1000
      genome_build: sacCer3
      individual: simulated

  variant_calling_accuracy:
    parameters:
      n_reads: 20000000
    plot_type: variant_calling_accuracy

  variant_calling_accuracy_test:
    parameters:
      n_reads: 100000
    plot_type: variant_calling_accuracy

  runtime:
    plot_type: runtime

  runtime_with_varying_number_of_threads:
    plot_type: runtime_with_varying_number_of_threads
    parameters:
      n_reads: "100000"

  accuracy_for_various_mapq_thresholds_human_whole_genome:
    title: "Precision/recall for various MAPQ thresholds"
    description: "Recall and 1-Precision is shown for different subsets of the reads, depending on the MAPQ-score 
    (shown as dots in the plot). For every MAPQ-score, only reads with that score or higher are included."
    plot_type: accuracy
    parameters:
      dataset_size: big
      n_reads: "1000000"

  runtime_human_whole_genome:
    title: "Runtime as a function of number of threads used"
    description: "Shown for single-end and paired-end reads and different read lengths."
    plot_type: runtime_with_varying_number_of_threads
    parameters:
      dataset_size: big
      n_reads: 10000000

  memory_human_whole_genome:
    title: "Memory usage"
    description: "Memory usage when mapping 2 million reads using 4 threads to hg38."
    plot_type: memory_usage
    parameters:
      dataset_size: big
      n_reads: 2000000
      n_threads: 4

  variant_calling_accuracy_human_whole_genome:
    plot_type: variant_calling_accuracy
    parameters:
      dataset_size: big
      n_reads: "5000000"

  accuracy_vs_read_length_and_error_profile_human_whole_genome:
    title: "Accuracy for different error profiles"
    description: "Showing read mapping accuracy for reads simulated with different error profiles (here described as low, medium and high error rate)."
    plot_type: accuracy_vs_read_length_and_error_profile
    parameters:
      dataset_size: big
      n_reads: "250000"
      
  variant_calling_accuracy_vs_mapq_threshold_quick:
    title: "Variant calling accuracy"
    decription: "Recall and 1-precision is shown after filtering the reads on various MAPQ-score before 
    calling variants with GATK. Accuracy is computed by hap.py after comparing the called variants against a truth set."
    plot_type: variant_calling_accuracy_vs_mapq_threshold
    parameters:
      dataset_size: small
      n_reads: "200000"
      n_threads: 2
      
  variant_calling_accuracy_vs_mapq_threshold:
    title: "Variant calling accuracy"
    decription: "Recall and 1-precision is shown after filtering the reads on various MAPQ-score before 
    calling variants with GATK. Accuracy is computed by hap.py after comparing the called variants against a truth set.
    In this experiments, a smaller genome of only chromosome 17-21 has been used."
    plot_type: variant_calling_accuracy_vs_mapq_threshold
    parameters:
      dataset_size: medium
      n_reads: 30000000
      n_threads: 8

  variant_calling_accuracy_vs_mapq_threshold_yeast:
    title: "Variant calling accuracy vs. MAPQ thresholds (yeast)"
    plot_type: variant_calling_accuracy_vs_mapq_threshold
    parameters:
      genome_build: sacCer3
      individual: simulated
      dataset_size: medium
      n_reads: "200000"
      n_threads: 8

  f1_score_vs_read_length:
    title: "Accuracy vs read length"
    description: "Accuracy is measured as the F1 score and shown for different read lengths and single/paired end reads. 
    Further divided into reads containing and not containing genomic variants. A read contains a variant is it has been 
    simulated so that it contains a variant allele not in the reference genome."
    plot_type: f1_score_vs_read_length
    parameters:
      read_length: [75, 100, 125, 150, 175, 200, 225, 250]
      n_threads: 4
      n_reads: 40000

  accuracy_for_various_mapq_thresholds_yeast:
    plot_type: accuracy
    parameters:
      genome_build: sacCer3
      individual: simulated

  peak_calling_accuracy_test:
    title: "Peak calling accuracy"
    description: "Showing the F1 score for each peak caller on some small simulated data."
    plot_type: peak_calling_accuracy
    parameters:
      genome_build: sacCer3
      individual: simulated
      n_peaks: 50

  peak_calling_accuracy_human:
    plot_type: peak_calling_accuracy
    parameters:
      n_peaks: 500

  peak_calling_accuracy_vs_read_length_human:
    title: "Peak calling accuracy"
    description: "Peaks are simulated using Chips. The accuracy is the number of peaks found after calling peaks by MACS and selecting the top N peaks where N is the same number of peaks as in the simulated data."
    plot_type: peak_calling_accuracy_vs_read_length
    parameters:
      read_length: [36, 75, 150]
      genome_build: hg38
      individual: hg002
      n_peaks: 500

  peak_calling_accuracy_vs_read_length_yeast:
    title: "Peak calling accuracy"
    description: "Peaks are simulated using Chips. The accuracy is the number of peaks found after calling peaks by MACS and selecting the top N peaks where N is the same number of peaks as in the simulated data."
    plot_type: peak_calling_accuracy_vs_read_length
    parameters:
      read_length: [36, 75, 150]
      genome_build: sacCer3
      individual: simulated
      n_peaks: 50



# The following defines different type of plots
# This includes only the description of the structure of each plot, not what values are used for the variables
# Each of x_axis, y_axis, category_variable, color, labels, facet_col, facet_row
# should be either a result_type or a parameter_type if set

plot_types:
  f1_score:
    type: bar
    x: "method"
    y: mapping_f1_score
  accuracy:
    type: line
    markers: True
    x: mapping_one_minus_precision
    y: mapping_recall
    labels: min_mapq
    color: method
    facet_col: variant_filter
    facet_row: read_type
    layout:
      xaxis_type: log
  accuracy_on_various_read_lengths:
    type: line
    markers: True
    x: mapping_one_minus_precision
    y: mapping_recall
    labels: min_mapq
    color: method
    facet_col: read_length
  accuracy_vs_read_length_single_method:
    type: line
    x: read_length
    y: mapping_f1_score
  accuracy_vs_read_length_and_error_profile:
    type: line
    x: read_length
    y: mapping_f1_score
    color: method
    facet_col: variant_filter
    facet_row: error_profile
  runtime:
    type: bar
    y: runtime
    x: method
  runtime_with_varying_number_of_threads:
    type: line
    y: runtime
    x: n_threads
    color: method
    facet_col: read_type
    facet_row: read_length
  memory_usage:
    type: bar
    y: memory_usage
    x: method
  variant_calling_accuracy:
    type: scatter
    y: variant_calling_recall
    x: variant_calling_one_minus_precision
    color: method
    facet_col: variant_calling_type
  accuracy_f1_score:
    type: bar
    y: mapping_f1_score
    x: method
    facet_col: read_type
  variant_calling_accuracy_vs_mapq_threshold:
    type: line
    markers: true
    y: variant_calling_recall
    x: variant_calling_one_minus_precision
    facet_row: variant_calling_type
    labels: min_mapq
    color: method
  f1_score_vs_read_length:
    type: line
    y: mapping_f1_score
    x: read_length
    color: method
    facet_col: variant_filter
    facet_row: read_type
  peak_calling_accuracy:
    type: bar
    x: method
    y: peak_calling_accuracy
  peak_calling_accuracy_vs_read_length:
    type: line
    color: method
    y: peak_calling_accuracy
    x: read_length
