
name: Benchmarks

on:
  # small benchmark on push and pull request
  push:
    branches: ["dev", "master"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          clean: false

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Run test
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.'
          snakefile: 'Snakefile'
          args: '--cores 16 --use-conda --rerun-incomplete reports/test.md'
          stagein: | # 'cd benchmarks' # additional preliminary commands to run (can be multiline)
            apt-get update
            apt-get -y install gcc
            python -m pip install --upgrade pip setuptools wheel
            pip install -r python_requirements.txt

      - name: Save benchmarks results
        run: |
          git config --local user.email "github@action.com"
          git config --local user.name "github action"
          git config pull.rebase false
          
          git add -f reports/*.md
          git add -f reports/presets/*.png
          git commit -am 'Benchmark results'
          
          #git pull -X ours origin benchmarks

      - name: Push results to benchmark branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
          force: true
          branch: benchmarks
